Modify JCifsMonitor to use a private method for getting a SmbFile object so we can override it in the unit tests. This gets around this error running the unit test under JDK 11:
[INFO] Running org.opennms.netmgt.poller.monitors.JCifsMonitorTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.81 s <<< FAILURE! - in org.opennms.netmgt.poller.monitors.JCifsMonitorTest
[ERROR] initializationError(org.opennms.netmgt.poller.monitors.JCifsMonitorTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ClassFormatError: Nest member class_info_index 83 has bad constant type in class file org/opennms/netmgt/poller/monitors/JCifsMonitor